/**
 * Curated quote-calculator appearance packs.
 * Each theme’s surfaces, text, borders, and accent are designed together
 * for contrast — picking a theme sets the whole calculator chrome.
 */

export type WidgetThemeTokens = {
  id: string
  name: string
  mode: 'light' | 'dark'
  /** One-line for admin picker */
  description: string
  brand: string
  brandText: string
  surfaceBase: string
  surfaceElevated: string
  surfaceHover: string
  surfaceMuted: string
  surfaceBorder: string
  surfaceBorderStrong: string
  textPrimary: string
  textSecondary: string
  textMuted: string
}

export const DEFAULT_WIDGET_THEME_ID = 'alabaster'

export const WIDGET_THEMES: WidgetThemeTokens[] = [
  {
    id: 'alabaster',
    name: 'Alabaster',
    mode: 'light',
    description: 'Warm gallery white — original ClosetQuote look',
    brand: '#5a6e5a',
    brandText: '#ffffff',
    surfaceBase: '#f8f7f5',
    surfaceElevated: '#ffffff',
    surfaceHover: '#f2f1ed',
    surfaceMuted: '#f3f4f6',
    surfaceBorder: '#d6d3cd',
    surfaceBorderStrong: '#bbb7ae',
    textPrimary: '#2d2d2d',
    textSecondary: '#6b6b63',
    textMuted: '#a8a8a0',
  },
  {
    id: 'gallery-white',
    name: 'Gallery White',
    mode: 'light',
    description: 'Cool crisp white with steel accent',
    brand: '#3d5a80',
    brandText: '#ffffff',
    surfaceBase: '#f4f6f8',
    surfaceElevated: '#ffffff',
    surfaceHover: '#eef1f4',
    surfaceMuted: '#e8ecf0',
    surfaceBorder: '#d0d7de',
    surfaceBorderStrong: '#afb8c1',
    textPrimary: '#1f2933',
    textSecondary: '#52606d',
    textMuted: '#9aa5b1',
  },
  {
    id: 'linen',
    name: 'Linen',
    mode: 'light',
    description: 'Soft natural linen with clay accent',
    brand: '#9c6b4a',
    brandText: '#ffffff',
    surfaceBase: '#f3efe8',
    surfaceElevated: '#faf7f2',
    surfaceHover: '#ebe4da',
    surfaceMuted: '#e5ddd2',
    surfaceBorder: '#d4c8b8',
    surfaceBorderStrong: '#b8a994',
    textPrimary: '#3a3228',
    textSecondary: '#6e6256',
    textMuted: '#9c8f80',
  },
  {
    id: 'parchment',
    name: 'Parchment',
    mode: 'light',
    description: 'Aged paper with ink accent',
    brand: '#4a3f35',
    brandText: '#f5f0e6',
    surfaceBase: '#f0ebe0',
    surfaceElevated: '#f7f3ea',
    surfaceHover: '#e8e1d2',
    surfaceMuted: '#ddd5c4',
    surfaceBorder: '#cfc4b0',
    surfaceBorderStrong: '#b0a48e',
    textPrimary: '#2c261f',
    textSecondary: '#5c5348',
    textMuted: '#8a8072',
  },
  {
    id: 'sage-atelier',
    name: 'Sage Atelier',
    mode: 'light',
    description: 'Muted sage surfaces with deeper green accent',
    brand: '#4f6f52',
    brandText: '#ffffff',
    surfaceBase: '#eef2ee',
    surfaceElevated: '#f7faf7',
    surfaceHover: '#e4ebe4',
    surfaceMuted: '#dce5dc',
    surfaceBorder: '#c5d0c5',
    surfaceBorderStrong: '#9aab9a',
    textPrimary: '#243028',
    textSecondary: '#55635a',
    textMuted: '#879489',
  },
  {
    id: 'coastal-mist',
    name: 'Coastal Mist',
    mode: 'light',
    description: 'Soft sea-glass with teal accent',
    brand: '#2a6f7a',
    brandText: '#ffffff',
    surfaceBase: '#eef5f6',
    surfaceElevated: '#f8fbfc',
    surfaceHover: '#e3eef0',
    surfaceMuted: '#d7e6e9',
    surfaceBorder: '#c0d4d8',
    surfaceBorderStrong: '#8fadb3',
    textPrimary: '#1c3338',
    textSecondary: '#4d6a70',
    textMuted: '#7f989d',
  },
  {
    id: 'arctic-frost',
    name: 'Arctic Frost',
    mode: 'light',
    description: 'Icy blue-gray with polar blue accent',
    brand: '#2563a8',
    brandText: '#ffffff',
    surfaceBase: '#f0f4f8',
    surfaceElevated: '#ffffff',
    surfaceHover: '#e6edf4',
    surfaceMuted: '#dce5ef',
    surfaceBorder: '#c5d1de',
    surfaceBorderStrong: '#96a8bc',
    textPrimary: '#1a2332',
    textSecondary: '#4a5d73',
    textMuted: '#8496ab',
  },
  {
    id: 'terracotta',
    name: 'Terracotta',
    mode: 'light',
    description: 'Sunbaked clay with warm earth accent',
    brand: '#c45c26',
    brandText: '#ffffff',
    surfaceBase: '#faf3ed',
    surfaceElevated: '#fffaf6',
    surfaceHover: '#f3e8de',
    surfaceMuted: '#ead9cb',
    surfaceBorder: '#dbc4b0',
    surfaceBorderStrong: '#c09a7c',
    textPrimary: '#3d2a1f',
    textSecondary: '#7a5642',
    textMuted: '#a8846c',
  },
  {
    id: 'ivory-brass',
    name: 'Ivory Brass',
    mode: 'light',
    description: 'Luxury ivory with brass accent',
    brand: '#a67c2d',
    brandText: '#1a1408',
    surfaceBase: '#f7f4ec',
    surfaceElevated: '#fffcf5',
    surfaceHover: '#efe9dc',
    surfaceMuted: '#e6dfce',
    surfaceBorder: '#d4cbb4',
    surfaceBorderStrong: '#b8ac8e',
    textPrimary: '#2a2418',
    textSecondary: '#6b614c',
    textMuted: '#9a8f78',
  },
  {
    id: 'slate-studio',
    name: 'Slate Studio',
    mode: 'light',
    description: 'Neutral slate workspace',
    brand: '#475569',
    brandText: '#ffffff',
    surfaceBase: '#f1f5f9',
    surfaceElevated: '#ffffff',
    surfaceHover: '#e8eef4',
    surfaceMuted: '#dde5ee',
    surfaceBorder: '#cbd5e1',
    surfaceBorderStrong: '#94a3b8',
    textPrimary: '#0f172a',
    textSecondary: '#475569',
    textMuted: '#94a3b8',
  },
  {
    id: 'charcoal-stage',
    name: 'Charcoal Stage',
    mode: 'dark',
    description: 'Dark AV stage — pairs with black sites',
    brand: '#d4a574',
    brandText: '#1a1208',
    surfaceBase: '#121212',
    surfaceElevated: '#1c1c1c',
    surfaceHover: '#262626',
    surfaceMuted: '#2a2a2a',
    surfaceBorder: '#333333',
    surfaceBorderStrong: '#4a4a4a',
    textPrimary: '#f2f2f2',
    textSecondary: '#a3a3a3',
    textMuted: '#6b6b6b',
  },
  {
    id: 'midnight-ink',
    name: 'Midnight Ink',
    mode: 'dark',
    description: 'Deep navy night with ice accent',
    brand: '#6eb6ff',
    brandText: '#0a1628',
    surfaceBase: '#0b1220',
    surfaceElevated: '#121a2b',
    surfaceHover: '#1a2438',
    surfaceMuted: '#1e2a40',
    surfaceBorder: '#243049',
    surfaceBorderStrong: '#3a4d6e',
    textPrimary: '#e8eef8',
    textSecondary: '#9aafc7',
    textMuted: '#6b8199',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    mode: 'dark',
    description: 'Near-black with cool silver accent',
    brand: '#c0c8d4',
    brandText: '#0e1014',
    surfaceBase: '#0a0a0b',
    surfaceElevated: '#141416',
    surfaceHover: '#1c1c1f',
    surfaceMuted: '#222226',
    surfaceBorder: '#2c2c32',
    surfaceBorderStrong: '#45454f',
    textPrimary: '#f0f0f2',
    textSecondary: '#a0a0ab',
    textMuted: '#6e6e7a',
  },
  {
    id: 'graphite',
    name: 'Graphite',
    mode: 'dark',
    description: 'Industrial dark gray with ember accent',
    brand: '#e85d04',
    brandText: '#1a0a00',
    surfaceBase: '#16181c',
    surfaceElevated: '#1e2228',
    surfaceHover: '#282d35',
    surfaceMuted: '#2e343d',
    surfaceBorder: '#3a414c',
    surfaceBorderStrong: '#556070',
    textPrimary: '#eceff3',
    textSecondary: '#9aa3b0',
    textMuted: '#6b7380',
  },
  {
    id: 'espresso',
    name: 'Espresso',
    mode: 'dark',
    description: 'Warm dark brown café',
    brand: '#d4a373',
    brandText: '#1a1008',
    surfaceBase: '#1a1410',
    surfaceElevated: '#241c16',
    surfaceHover: '#2e241c',
    surfaceMuted: '#342a20',
    surfaceBorder: '#3d3228',
    surfaceBorderStrong: '#5c4a3a',
    textPrimary: '#f3ebe3',
    textSecondary: '#b8a090',
    textMuted: '#7d6a58',
  },
  {
    id: 'forest-night',
    name: 'Forest Night',
    mode: 'dark',
    description: 'Deep woodland with moss accent',
    brand: '#7cb87c',
    brandText: '#0c160c',
    surfaceBase: '#0e1410',
    surfaceElevated: '#161e18',
    surfaceHover: '#1e2820',
    surfaceMuted: '#243028',
    surfaceBorder: '#2c3a30',
    surfaceBorderStrong: '#45604a',
    textPrimary: '#e6f0e6',
    textSecondary: '#9ab09a',
    textMuted: '#6a806a',
  },
  {
    id: 'ocean-dusk',
    name: 'Ocean Dusk',
    mode: 'dark',
    description: 'Deep teal dusk with aqua accent',
    brand: '#3ecfcf',
    brandText: '#042020',
    surfaceBase: '#0a1618',
    surfaceElevated: '#122022',
    surfaceHover: '#1a2c2e',
    surfaceMuted: '#203638',
    surfaceBorder: '#284244',
    surfaceBorderStrong: '#3a6064',
    textPrimary: '#e4f4f4',
    textSecondary: '#8eb8b8',
    textMuted: '#5a8080',
  },
  {
    id: 'copper-loft',
    name: 'Copper Loft',
    mode: 'dark',
    description: 'Dark loft with copper accent',
    brand: '#c77b4a',
    brandText: '#1a0e06',
    surfaceBase: '#141210',
    surfaceElevated: '#1e1a16',
    surfaceHover: '#2a2420',
    surfaceMuted: '#322c26',
    surfaceBorder: '#3e3630',
    surfaceBorderStrong: '#5c4e42',
    textPrimary: '#f2ebe4',
    textSecondary: '#b0a090',
    textMuted: '#7a6c5c',
  },
  {
    id: 'noir-brass',
    name: 'Noir Brass',
    mode: 'dark',
    description: 'Black-tie dark with brass accent',
    brand: '#c9a227',
    brandText: '#1a1400',
    surfaceBase: '#0d0d0d',
    surfaceElevated: '#171717',
    surfaceHover: '#222222',
    surfaceMuted: '#2a2a2a',
    surfaceBorder: '#333333',
    surfaceBorderStrong: '#4d4d4d',
    textPrimary: '#f5f0e0',
    textSecondary: '#b8ae90',
    textMuted: '#7a7460',
  },
  {
    id: 'velvet-cinema',
    name: 'Velvet Cinema',
    mode: 'dark',
    description: 'Home-theater dark with warm rose accent',
    brand: '#e07a7a',
    brandText: '#1a0808',
    surfaceBase: '#100e12',
    surfaceElevated: '#1a161c',
    surfaceHover: '#242028',
    surfaceMuted: '#2c2830',
    surfaceBorder: '#3a343f',
    surfaceBorderStrong: '#564e5c',
    textPrimary: '#f4eef2',
    textSecondary: '#b4a4b0',
    textMuted: '#7a6e78',
  },
]

const BY_ID = new Map(WIDGET_THEMES.map((t) => [t.id, t]))

export function isWidgetThemeId(value: unknown): value is string {
  return typeof value === 'string' && BY_ID.has(value)
}

export function resolveWidgetTheme(id: string | null | undefined): WidgetThemeTokens {
  if (id && BY_ID.has(id)) return BY_ID.get(id)!
  return BY_ID.get(DEFAULT_WIDGET_THEME_ID)!
}

/** CSS custom properties applied on the widget root. */
export function widgetThemeToCssVars(theme: WidgetThemeTokens): Record<string, string> {
  return {
    '--brand-color': theme.brand,
    '--brand-text-color': theme.brandText,
    '--color-surface-base': theme.surfaceBase,
    '--color-surface-elevated': theme.surfaceElevated,
    '--color-surface-hover': theme.surfaceHover,
    '--color-surface-muted': theme.surfaceMuted,
    '--color-surface-border': theme.surfaceBorder,
    '--color-surface-border-strong': theme.surfaceBorderStrong,
    '--color-text-primary': theme.textPrimary,
    '--color-text-secondary': theme.textSecondary,
    '--color-text-muted': theme.textMuted,
  }
}

export function listWidgetThemesForAdmin(): Array<{
  id: string
  name: string
  mode: 'light' | 'dark'
  description: string
  brand: string
  surfaceBase: string
  surfaceElevated: string
  textPrimary: string
}> {
  return WIDGET_THEMES.map((t) => ({
    id: t.id,
    name: t.name,
    mode: t.mode,
    description: t.description,
    brand: t.brand,
    surfaceBase: t.surfaceBase,
    surfaceElevated: t.surfaceElevated,
    textPrimary: t.textPrimary,
  }))
}
